version: '3'

services:
    app:
        depends_on:
            - postgresql

    postgresql:
        build:
            context: ./docker/db
            dockerfile: Dockerfile.postgresql
        volumes:
            - ./.data/postgresql:/var/lib/postgresql/data:rw
        env_file:
            - .env
        ports:
            - "5432:5432"
